### ISSUE TITLE
数据库脚本没有吗，前端有mock demo数据也没

### ISSUE THREAD

**Issue by hshe** [tx7do/kratos-cms#1]
![image](https://user-images.githubusercontent.com/8075773/187059571-7d9aacc4-c4b1-4faa-9a9b-e82c99500b3f.png)

**Comment by tx7do** [comment]
哈哈哈，是还没有。晚点加个koa做mock server。
数据库全都由迁移工具生成，还没做sql。

**Comment by Ymriri** [comment]
楼主咕咕多久了，呜呜呜，啥时候补数据库

**Comment by tx7do** [comment]
> 楼主咕咕多久了，呜呜呜，啥时候补数据库

我也想捯饬一下，奈何没时间。

**Comment by Ymriri** [comment]
催更，不然跑起来也没用，看了下还挺不错的项目
