### ISSUE TITLE
Can you export API json?

### ISSUE THREAD

**Issue by bdviett** [tx7do/kratos-cms#13]
I want this api mock, can you export it, thanks!

**Comment by tx7do** [comment]
https://github.com/tx7do/kratos-cms/blob/main/blog-backend/app/admin/service/cmd/server/assets/openapi.yaml
https://github.com/tx7do/kratos-cms/blob/main/blog-backend/app/front/service/cmd/server/assets/openapi.yaml

u need learn about [Swagger UI](https://swagger.io/tools/swagger-ui/).

**Comment by bdviett** [comment]
Thanks @tx7do. I got it.
Are you have mock database or data.sql?

**Comment by tx7do** [comment]
u can use this tool:<https://apifox.com/>.
this tool support: Mock.
