### ISSUE TITLE
你好问下后面还会再更新吗？

### ISSUE THREAD

**Issue by weitemi** [tx7do/kratos-cms#5]
你好问下后面还会再更吗，项目跑起来了，真心的好，一看就是做大项目的经验开发。

**Comment by tx7do** [comment]
更新肯定是会继续的更新的，因为我自己也在用。所以，改进将会是持续的。

weimite ***@***.***> 于2023年9月12日周二 16:14写道：

**Comment by weitemi** [comment]
感谢分享。
