### ISSUE TITLE
喵酱 PGV 的校验消息如何翻译成中文呢

### ISSUE THREAD

**Issue by lgcshy** [tx7do/kratos-cms#7]
RT

引入validate.Validator()中间件后，想把英文错误消息转成中文
`{
    "code": 400,
    "reason": "VALIDATOR",
    "message": "invalid CreatePositionRequest.Position: embedded message failed validation | caused by: invalid Position.Code: value length must be between 2 and 50 runes, inclusive"
}`

**Comment by tx7do** [comment]
😂你可以接一个翻译软件的接口。。。。

aFog ***@***.***> 于2023年10月11日周三 16:29写道：

**Comment by lgcshy** [comment]
hahah 不错的注意~~ 目前做mapping翻译 有点烦 想着有没有最佳实践方案

**Comment by tx7do** [comment]
你可以fork一下，然后。。。。自己改一下。

aFog ***@***.***> 于2023年10月12日周四 20:01写道：
